# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.resize(430, 425)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WelcomeWindow.sizePolicy().hasHeightForWidth())
        WelcomeWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(WelcomeWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_pushButtons = QtWidgets.QVBoxLayout()
        self.verticalLayout_pushButtons.setObjectName("verticalLayout_pushButtons")
        self.details_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.details_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_pushButton.sizePolicy().hasHeightForWidth())
        self.details_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Formular")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.details_pushButton.setFont(font)
        self.details_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.details_pushButton.setStyleSheet("QPushButton#junction_boxes_pushButton, #exit_pushButton, #details_pushButton, #remote_controls_pushButton, #power_box_pushButton, #fixtures_pushButton #scripts_pushButton{\n"
"background-color: rgb(98, 208, 223);\n"
"color:rgba(255,255,255,210);\n"
"font: 10pt \"Formular\";\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#junction_boxes_pushButton:hover, #exit_pushButton:hover, #details_pushButton:hover, #remote_controls_pushButton:hover, power_box_pushButton:hover, #fixtures_pushButton:hover #scripts_pushButton:hover{\n"
"background-color: rgb(255, 131, 0);\n"
"border-radius:10px;\n"
"}")
        self.details_pushButton.setObjectName("details_pushButton")
        self.verticalLayout_pushButtons.addWidget(self.details_pushButton)
        self.junction_boxes_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.junction_boxes_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.junction_boxes_pushButton.sizePolicy().hasHeightForWidth())
        self.junction_boxes_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Formular")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.junction_boxes_pushButton.setFont(font)
        self.junction_boxes_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.junction_boxes_pushButton.setStyleSheet("QPushButton#junction_boxes_pushButton, #exit_pushButton, #details_pushButton, #remote_controls_pushButton, #power_box_pushButton, #fixtures_pushButton {\n"
"background-color: rgb(98, 208, 223);\n"
"color:rgba(255,255,255,210);\n"
"font: 10pt \"Formular\";\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#junction_boxes_pushButton:hover, #exit_pushButton:hover, #details_pushButton:hover, #remote_controls_pushButton:hover, power_box_pushButton:hover, #fixtures_pushButton:hover {\n"
"background-color: rgb(255, 131, 0);\n"
"border-radius:10px;\n"
"}")
        self.junction_boxes_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.junction_boxes_pushButton.setObjectName("junction_boxes_pushButton")
        self.verticalLayout_pushButtons.addWidget(self.junction_boxes_pushButton)
        self.remote_controls_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.remote_controls_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remote_controls_pushButton.sizePolicy().hasHeightForWidth())
        self.remote_controls_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Formular")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.remote_controls_pushButton.setFont(font)
        self.remote_controls_pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.remote_controls_pushButton.setStyleSheet("QPushButton#junction_boxes_pushButton, #exit_pushButton, #details_pushButton, #remote_controls_pushButton, #power_box_pushButton, #fixtures_pushButton {\n"
"background-color: rgb(98, 208, 223);\n"
"color:rgba(255,255,255,210);\n"
"font: 10pt \"Formular\";\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#junction_boxes_pushButton:hover, #exit_pushButton:hover, #details_pushButton:hover, #remote_controls_pushButton:hover, power_box_pushButton:hover, #fixtures_pushButton:hover {\n"
"background-color: rgb(255, 131, 0);\n"
"border-radius:10px;\n"
"}")
        self.remote_controls_pushButton.setObjectName("remote_controls_pushButton")
        self.verticalLayout_pushButtons.addWidget(self.remote_controls_pushButton)
        self.panel_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.panel_pushButton.setStyleSheet("QPushButton#junction_boxes_pushButton, #exit_pushButton, #details_pushButton, #remote_controls_pushButton, #power_box_pushButton, #fixtures_pushButton,#panel_pushButton {\n"
"background-color: rgb(98, 208, 223);\n"
"color:rgba(255,255,255,210);\n"
"font: 10pt \"Formular\";\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#junction_boxes_pushButton:hover, #exit_pushButton:hover, #details_pushButton:hover, #remote_controls_pushButton:hover, power_box_pushButton:hover, #fixtures_pushButton:hover,\n"
"#panel_pushButton:hover {\n"
"background-color: rgb(255, 131, 0);\n"
"border-radius:10px;\n"
"}")
        self.panel_pushButton.setObjectName("panel_pushButton")
        self.verticalLayout_pushButtons.addWidget(self.panel_pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_pushButtons)
        self.fixtures_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.fixtures_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixtures_pushButton.sizePolicy().hasHeightForWidth())
        self.fixtures_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Formular")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fixtures_pushButton.setFont(font)
        self.fixtures_pushButton.setStyleSheet("QPushButton#junction_boxes_pushButton, #exit_pushButton, #details_pushButton, #remote_controls_pushButton, #power_box_pushButton, #fixtures_pushButton {\n"
"background-color: rgb(98, 208, 223);\n"
"color:rgba(255,255,255,210);\n"
"font: 10pt \"Formular\";\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#junction_boxes_pushButton:hover, #exit_pushButton:hover, #details_pushButton:hover, #remote_controls_pushButton:hover, power_box_pushButton:hover, #fixtures_pushButton:hover {\n"
"background-color: rgb(255, 131, 0);\n"
"border-radius:10px;\n"
"}")
        self.fixtures_pushButton.setObjectName("fixtures_pushButton")
        self.verticalLayout_2.addWidget(self.fixtures_pushButton)
        self.scripts_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.scripts_pushButton.setStyleSheet("QPushButton#junction_boxes_pushButton, #exit_pushButton, #details_pushButton, #remote_controls_pushButton, #power_box_pushButton, #fixtures_pushButton, #scripts_pushButton\n"
"{\n"
"background-color: rgb(98, 208, 223);\n"
"color:rgba(255,255,255,210);\n"
"font: 10pt \"Formular\";\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#junction_boxes_pushButton:hover, #exit_pushButton:hover, #details_pushButton:hover, #remote_controls_pushButton:hover, power_box_pushButton:hover, #fixtures_pushButton:hover, #scripts_pushButton:hover\n"
"{\n"
"background-color: rgb(255, 131, 0);\n"
"border-radius:10px;\n"
"}")
        self.scripts_pushButton.setObjectName("scripts_pushButton")
        self.verticalLayout_2.addWidget(self.scripts_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.authentication_QWidget = QtWidgets.QWidget(self.centralwidget)
        self.authentication_QWidget.setObjectName("authentication_QWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.authentication_QWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.username_QWidget = QtWidgets.QWidget(self.authentication_QWidget)
        self.username_QWidget.setObjectName("username_QWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.username_QWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_QLabel = QtWidgets.QLabel(self.username_QWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_QLabel.sizePolicy().hasHeightForWidth())
        self.username_QLabel.setSizePolicy(sizePolicy)
        self.username_QLabel.setMaximumSize(QtCore.QSize(120, 120))
        self.username_QLabel.setObjectName("username_QLabel")
        self.horizontalLayout.addWidget(self.username_QLabel)
        self.username_QLineEdit = QtWidgets.QLineEdit(self.username_QWidget)
        self.username_QLineEdit.setMaximumSize(QtCore.QSize(300, 100))
        self.username_QLineEdit.setMaxLength(100)
        self.username_QLineEdit.setObjectName("username_QLineEdit")
        self.horizontalLayout.addWidget(self.username_QLineEdit)
        self.verticalLayout_3.addWidget(self.username_QWidget)
        self.number_task_QWidget = QtWidgets.QWidget(self.authentication_QWidget)
        self.number_task_QWidget.setObjectName("number_task_QWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.number_task_QWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.number_task_TEXT = QtWidgets.QLabel(self.number_task_QWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_task_TEXT.sizePolicy().hasHeightForWidth())
        self.number_task_TEXT.setSizePolicy(sizePolicy)
        self.number_task_TEXT.setMaximumSize(QtCore.QSize(120, 16777215))
        self.number_task_TEXT.setObjectName("number_task_TEXT")
        self.horizontalLayout_3.addWidget(self.number_task_TEXT)
        self.number_task_QLineEdit = QtWidgets.QLineEdit(self.number_task_QWidget)
        self.number_task_QLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.number_task_QLineEdit.setObjectName("number_task_QLineEdit")
        self.horizontalLayout_3.addWidget(self.number_task_QLineEdit)
        self.verticalLayout_3.addWidget(self.number_task_QWidget)
        self.position_number_QWidget = QtWidgets.QWidget(self.authentication_QWidget)
        self.position_number_QWidget.setObjectName("position_number_QWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.position_number_QWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.position_number_QLabel = QtWidgets.QLabel(self.position_number_QWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_number_QLabel.sizePolicy().hasHeightForWidth())
        self.position_number_QLabel.setSizePolicy(sizePolicy)
        self.position_number_QLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.position_number_QLabel.setObjectName("position_number_QLabel")
        self.horizontalLayout_5.addWidget(self.position_number_QLabel)
        self.position_number_QLineEdit = QtWidgets.QLineEdit(self.position_number_QWidget)
        self.position_number_QLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.position_number_QLineEdit.setObjectName("position_number_QLineEdit")
        self.horizontalLayout_5.addWidget(self.position_number_QLineEdit)
        self.verticalLayout_3.addWidget(self.position_number_QWidget)
        self.verticalLayout_2.addWidget(self.authentication_QWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.SAPR_SPECMASH_TEXT = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SAPR_SPECMASH_TEXT.sizePolicy().hasHeightForWidth())
        self.SAPR_SPECMASH_TEXT.setSizePolicy(sizePolicy)
        self.SAPR_SPECMASH_TEXT.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("GOST type A")
        font.setPointSize(10)
        self.SAPR_SPECMASH_TEXT.setFont(font)
        self.SAPR_SPECMASH_TEXT.setObjectName("SAPR_SPECMASH_TEXT")
        self.horizontalLayout_2.addWidget(self.SAPR_SPECMASH_TEXT)
        self.SAPR_VER = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SAPR_VER.sizePolicy().hasHeightForWidth())
        self.SAPR_VER.setSizePolicy(sizePolicy)
        self.SAPR_VER.setMaximumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setFamily("GOST type A")
        font.setPointSize(10)
        self.SAPR_VER.setFont(font)
        self.SAPR_VER.setObjectName("SAPR_VER")
        self.horizontalLayout_2.addWidget(self.SAPR_VER)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.exit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exit_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_pushButton.sizePolicy().hasHeightForWidth())
        self.exit_pushButton.setSizePolicy(sizePolicy)
        self.exit_pushButton.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Formular")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.exit_pushButton.setFont(font)
        self.exit_pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.exit_pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.exit_pushButton.setStyleSheet("QPushButton#junction_boxes_pushButton, #exit_pushButton, #details_pushButton, #remote_controls_pushButton, #power_box_pushButton, #fixtures_pushButton {\n"
"background-color: rgb(98, 208, 223);\n"
"color:rgba(255,255,255,210);\n"
"font: 10pt \"Formular\";\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#junction_boxes_pushButton:hover, #exit_pushButton:hover, #details_pushButton:hover, #remote_controls_pushButton:hover, power_box_pushButton:hover, #fixtures_pushButton:hover {\n"
"background-color: rgb(255, 131, 0);\n"
"border-radius:10px;\n"
"}")
        self.exit_pushButton.setIconSize(QtCore.QSize(50, 50))
        self.exit_pushButton.setAutoDefault(False)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.verticalLayout_2.addWidget(self.exit_pushButton)
        WelcomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "MainWindow"))
        self.details_pushButton.setText(_translate("WelcomeWindow", "Детали"))
        self.junction_boxes_pushButton.setText(_translate("WelcomeWindow", "Клеммные коробки"))
        self.remote_controls_pushButton.setText(_translate("WelcomeWindow", "Пульты"))
        self.panel_pushButton.setText(_translate("WelcomeWindow", "Шкафы"))
        self.fixtures_pushButton.setText(_translate("WelcomeWindow", "Светильники"))
        self.scripts_pushButton.setText(_translate("WelcomeWindow", "Скрипты"))
        self.username_QLabel.setText(_translate("WelcomeWindow", "Исполнитель"))
        self.number_task_TEXT.setText(_translate("WelcomeWindow", "Номер заявки"))
        self.position_number_QLabel.setText(_translate("WelcomeWindow", "Номер позиции"))
        self.SAPR_SPECMASH_TEXT.setText(_translate("WelcomeWindow", "САПР \"СПЕЦМАШ\" "))
        self.SAPR_VER.setText(_translate("WelcomeWindow", "v.0.001"))
        self.exit_pushButton.setText(_translate("WelcomeWindow", "Выход"))
